FROM golang
RUN ["apt-get", "update"]
RUN ["apt-get", "install","apt-file", "-y"]
RUN ["apt-file", "update"] 
RUN ["apt-get", "install", "vim", "-y"]
RUN ["cd", "/go/src/" ] 
RUN ["git", "clone", "https://github.com/mayelespino/code.git"]