# https://www.cloudbees.com/blog/how-to-install-and-run-jenkins-with-docker-compose
# docker-compose.yaml
  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: mayel
      ports:
       - 8080:8080
       - 50000:50000
    container_name: jenkins
    volumes:
      - /home/mayel/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
